services:
  postgres:
    image: postgres:16
    container_name: toolschallenge-postgres
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USERNAME}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - toolschallenge-postgres-data:/var/lib/postgresql/data
      - ./docker/init-db:/docker-entrypoint-initdb.d

  toolschallenge:
    build: .
    container_name: toolschallenge-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${APP_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${APP_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${APP_DB_PASSWORD}
      #SPRING_PROFILES_ACTIVE: DEV
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  toolschallenge-postgres-data:

